version: '3.1'

services:

  postgres:
    image: postgres
    container_name: sample-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${PWD}/db/initdb.d:/docker-entrypoint-initdb.d

  mosquitto:
    image: eclipse-mosquitto
    container_name: sample-broker
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${PWD}/broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  api:
    image: api
    build: api/docker/api
    container_name: api
    restart: always
    environment:
      LOG_LEVEL: debug
      PG_CONNECT_STRING: postgres://sample:password@172.17.0.1:5432/sample
      PORT: 8080
    ports:
      - 8080:8080

  tractor-device:
    image: device
    build: devices/docker/device
    container_name: tractor-device
    restart: always
    environment:
      LOG_LEVEL: debug
      CONFIG_FILE: /opt/device/config.json
    volumes:
      - ${PWD}/devices/src/config/tractor.json:/opt/device/config.json

  warehouse-device:
    image: device
    build: devices/docker/device
    container_name: warehouse-device
    restart: always
    environment:
      LOG_LEVEL: debug
      CONFIG_FILE: /opt/device/config.json
    volumes:
      - ${PWD}/devices/src/config/warehouse.json:/opt/device/config.json

  tractor-controller:
    image: controller
    build: controllers/docker/controller
    container_name: tractor-controller
    restart: always
    environment:
      MQTT_HOSTNAME: 172.17.0.1
      MQTT_PORT: 1883
      PG_CONNECTION_STRING: postgresql://sample:password@172.17.0.1:5432/sample
      MQTT_KEEPALIVE_INTERVAL: 60
      MQTT_SUB_TOPIC: farm/tractor/#
      HANDLER_CONFIG_FILE: /opt/controller/config.json
    volumes:
      - ${PWD}/controllers/config/tractor.json:/opt/controller/config.json

  warehouse-controller:
    image: controller
    build: controllers/docker/controller
    container_name: warehouse-controller
    restart: always
    environment:
      MQTT_HOSTNAME: 172.17.0.1
      MQTT_PORT: 1883
      PG_CONNECTION_STRING: postgresql://sample:password@172.17.0.1:5432/sample
      MQTT_KEEPALIVE_INTERVAL: 60
      MQTT_SUB_TOPIC: farm/warehouse/#
      HANDLER_CONFIG_FILE: /opt/controller/config.json
    volumes:
      - ${PWD}/controllers/config/warehouse.json:/opt/controller/config.json
