version: '3.1'

services:

  postgres:
    image: postgres
    container_name: sample-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ${PWD}/db/initdb.d:/docker-entrypoint-initdb.d

  mosquitto:
    image: eclipse-mosquitto
    container_name: sample-broker
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${PWD}/broker/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
