# Tractor Device Makefile

package:
	@echo "==> Building package"
	@npm run compile
	@echo "Done."

depend:
	@echo "==> Installing dependencies"
	@npm install --no-package-lock
	@echo "Done."

.PHONY: package depend
